name: AdvancedStatus
main: paulevs.status.AdvancedStatus
version: 1.0.0
author: paulevs
description: "Plugin that changes player status outlook to make it better"
license: MIT
website: http://www.myhomepage.com