name: AdvancedStatus
main: paulevs.status.AdvancedStatus
version: 0.3.1
author: paulevs
description: "Plugin that changes player status outlook to make it better"
license: MIT
website: https://github.com/paulevsGitch/AdvancedStatusPlugin